apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: react-app
  labels:
    app: react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app-container2
          image: muhammadelmansi/react-app2:v1
          ports:
            - containerPort: 80