apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: react-app
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010